name:                aoc
version:             0.1.1.0
github:              "sangster/adventofcode.com"
license:             BSD3
author:              "Jon Sangster"
copyright:           "GPL-3"

data-files:
  - inputs/2018/*
  - inputs/2019/*
  - inputs/2020/*
  - inputs/2021/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/sangster/adventofcode.com#readme>

dependencies:
  - ansi-terminal
  - arithmoi
  - array
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-default
  - dequeue
  - extra
  - file-embed
  - hashable
  - hashtables
  - mtl
  - parallel
  - pqueue
  - primitive
  - safe
  - split
  - template-haskell >= 2.14
  - timeit
  - transformers
  - unordered-containers
  - utf8-string
  - vector

library:
  source-dirs: src

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -O2
      - -optc-O3
      - -optc-ffast-math
      - -Wall
    dependencies:
      - aoc
