name:                aoc2019
version:             0.1.0.0
github:              "sangster/aoc2019"
license:             BSD3
author:              "Jon Sangster"
maintainer:          "jon@ertt.ca"
copyright:           "GPL-3"

extra-source-files:
  - README.md
  - ChangeLog.md

data-files:
  - data/inputs/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sangster/aoc2019#readme>

dependencies:
  - array
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-default
  - file-embed
  - regex
  - regex-with-pcre
  - safe
  - utf8-string

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - aoc2019
      - test-framework
      - test-framework-hunit
      - HUnit
      - util

benchmarks:
  aoc2019-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - aoc2019
      - criterion
